Issue 6189 - CI tests fail with `[Errno 2] No such file or directory: '/var/cache/dnf/metadata_lock.pid'`
Bug Description:
There is an intermittent issue during container startup in our CI:
```
[Errno 2] No such file or directory: '/var/cache/dnf/metadata_lock.pid'
Error: Process completed with exit code 1.
```

`systemd` is not fully initialized when a second command runs and expects
a pid file to be available.
The script should wait until `systemctl is-system-running` is successful.

Fix Description:
Add a check for `systemctl is-system-running`.

Fixes: https://github.com/389ds/389-ds-base/issues/6189

Reviewed by: @progier389, @droideck (Thanks!)