Issue 4253 - Container bind mount schema
Bug Description:
When you mount a volume with schema into container, instance creation fails with:
```
Traceback (most recent call last):
  File "/usr/libexec/dirsrv/dscontainer", line 489, in <module>
    begin_magic()
    ~~~~~~~~~~~^^
  File "/usr/libexec/dirsrv/dscontainer", line 279, in begin_magic
    if not sds.create_from_args(g2b.collect(), s2b.collect()):
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lib389/instance/setup.py", line 759, in create_from_args
    self._install_ds(general, slapd, backends)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lib389/instance/setup.py", line 903, in _install_ds
    _ds_shutil_copytree(os.path.join(slapd['sysconf_dir'], 'dirsrv/schema'), slapd['schema_dir'])
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lib389/__init__.py", line 230, in _ds_shutil_copytree
    os.makedirs(dst)
    ~~~~~~~~~~~^^^^^
  File "<frozen os>", line 227, in makedirs
FileExistsError: [Errno 17] File exists: '/etc/dirsrv/slapd-localhost/schema'
```

`_ds_shutil_copytree()` is an outdated copy of the `shutil.copytree()` from Python 3.5.
In the later versions `dirs_exist_ok` parameter was introduced, but it was never backported
to our implementation.

Fix Description:
Instead of the custom implementation, use standard `shutil.copytree()` function, but ignore
existing directories (`dirs_exist_ok=True`) and use `copy` instead of `copy2` to ignore
file metadata.

Fixes: https://github.com/389ds/389-ds-base/issues/4253

Reviewed by: @mreynolds389, @droideck (Thanks!)