rpm.mk: Restore back LEGACY_ON
Bug Description:

Legacy perl tools are defined and can be built in `1.4.3` branch.
Moreover, legacy tools are still in RPM spec for that branch and thus,
RPM build is broken due to removed `LEGACY_ON`:
```
error: parse error in expression:  __LEGACY_ON__
error:                             ^
error: /__w/389-ds-base/389-ds-base/rpmbuild/SPECS/389-ds-base.spec:230: bad %if condition:  __LEGACY_ON__
```

Fix Description:
Restore back `LEGACY_ON` as it was in pre
e81985f71dacba9a6d19f0e52eaebeced5d15738.

Reviewed by:

Signed-off-by: Stanislav Levin <slev@altlinux.org>