Issue 50818 - dsconf pwdpolicy get error
Description:  When trying to retrieve a global or local policy we now see:

                policyError: 'PwPolicyManager' object has no attribute 'get_attr_list'

              Someone removed the function get_attr_list() along the way.
              Added the same logic back, and improved it to only report attributes
              that are set.

relates: https://pagure.io/389-ds-base/issue/50818

Reviewed by: spichugi(Thanks!)