Issue 6254 - Enabling replication for a sub suffix crashes browser (#6255)
Bug Description: Web Console: Enabling replication for a sub-suffix causes
TypeError: this.props.data.nsds5replicabinddn is not iterable.

Fix Description: Make sure that loadSuffixTree is run for subsuffixes, too.
Set defaults if data is absent.

Fixes: https://github.com/389ds/389-ds-base/issues/6254

Reviewed by: @progier389 (Thanks!)