Ticket bz1358565 -  clear and unsalted password types are vulnerable to timing attack
Description: Build fails with the commit f0e03b5a51972a125fe78f448d1f68e288782d1e:
  error: 'for' loop initial declarations are only allowed in C99 mode
  for (size_t i = 0; i < n; i++) {
  ^
Moved "size_t i;" to the top of slapi_ct_memcmp.

(cherry picked from commit 53da6d718b3dfee6cdd78e112d1926e90d03128a)