Issue 6997 - Logic error in get_bdb_impl_status prevents bdb2mdb execution (#6998)
Bug Description:
On F41 and F42 migration to MDB fails:
```
dsctl localhost dblib bdb2mdb
Berkeley Database library is not available. Maybe 389-ds-base-bdb rpm should be installed.
Error: Berkeley Database library is not available
```

This happens because `BDB_IMPL_STATUS.NONE` gets returned earlier than
we check for presence of the standard libdb provided by the system.

Fix Description:
Rewrite the logic to return `BDB_IMPL_STATUS.NONE` only when no working
BDB implementation is found.

Fixes: https://github.com/389ds/389-ds-base/issues/6997

Reviewed by: @progier389 (Thanks!)