Issue 5859 - dbscan fails with AttributeError: 'list' object has no attribute 'extends'
Bug Description:
There is a typo in dbscan:
```
>           cmd.extends(['-f', indexfile])
E           AttributeError: 'list' object has no attribute 'extends'

src/lib389/lib389/__init__.py:3057: AttributeError
```

Fix Description:
Fix the typo and fix the test
dirsrvtests/tests/suites/password/regression_test.py::test_unhashed_pw_switch

Fixes: https://github.com/389ds/389-ds-base/issues/5859

Reviewed-by: @progier389 (Thanks!)