Issue 5149 - Build failure on EL8 - undefined reference to `twalk_r'
Description:
back-ldbm uses `twalk_r` which is only available in glibc-2.30 or
higher. This results in a compilation warning and a linking error on
systems where this symbol is not available, for example EL8.

Fix Description:
* Add an autoconf check for the required symbol
* Add an explicit requirement for glibc => 2.30 in the spec file.

Fixes: https://github.com/389ds/389-ds-base/issues/5149

Reviewed by: @mreynolds389 (Thanks!)