Issue 6368 - fix basic test suite
Bug Description:
Basic test suite started to error out:

>               target_be = CustomSetup._search_be(backend_options, backend)
E               TypeError: CustomSetup._search_be() missing 1 required positional argument: 'beinfo'

Fix Description:
Add missing argument.

Relates: https://github.com/389ds/389-ds-base/issues/6368

Reviewed by: @progier389, @droideck (Thanks!)