Issue 4229 - Fix Rust linking
Description:  Fixed a build problem related to:
                  - undefined reference to symbol
                  - error adding symbols: DSO missing from command line

Relates: https://github.com/389ds/389-ds-base/issues/4229

Reviewed by: mreynolds