Issue 5120 - Fix compilation error
Bug Description:
Compilation fails with `-Wunused-function`:

```
ldap/servers/slapd/main.c:290:1: warning: ‘referral_set_defaults’ defined but not used [-Wunused-function]
  290 | referral_set_defaults(void)
      | ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:4148: all] Error 2
```

Fix Description:
Remove unused function `referral_set_defaults`.

Fixes: https://github.com/389ds/389-ds-base/issues/5120

Reviewed by: @progier389 (Thanks!)