Issue 5465 - Fix dbscan linking (#5466)
Bug Description:

Linking of dbscan fails with:
ld: ./.libs/libback-ldbm.so: undefined reference to symbol 'slapi_ch_free'
ld: ./.libs/libslapd.so.0: error adding symbols: DSO missing from command line

Fix Description:

Add the missing libslapd.so to the command line.

relates: https://github.com/389ds/389-ds-base/issues/5465

Author: Stanislav Levin

Reviewed by: Mark Reynolds (thanks)

(cherry picked from commit a942379b69600c4827268357e894b548271d2013)