Issue 5279 - dscontainer: TypeError: unsupported operand type(s) for /: 'str' and 'int'
Bug Description:
When DS_STARTUP_TIMEOUT is specified, dscontainer fails with:

TypeError: unsupported operand type(s) for /: 'str' and 'int'

Fix Description:
os.getenv returns a string when a variable is present, so the value
must be converted to int.

Fixes: https://github.com/389ds/389-ds-base/issues/5279

Reviewed by: @Firstyear (Thanks!)