Issue 5249 - dscontainer: ImportError: cannot import name 'get_default_db_lib' from 'lib389.utils'
Description:
A cherry picked commit from master ebc8ff4 introduced a regression
in 389-ds-base-2.0 branch:

```
Traceback (most recent call last):
  File "/usr/libexec/dirsrv/dscontainer", line 46, in <module>
    from lib389.utils import get_default_db_lib
ImportError: cannot import name 'get_default_db_lib' from 'lib389.utils' (/usr/lib/python3.10/site-packages/lib389/utils.py)
```

`get_default_db_lib()` and support for mdb doesn't exist in 2.0,
so we should remove this check from `dscontainer`.

Fixes: https://github.com/389ds/389-ds-base/issues/5249

Reviewed by: @mreynolds389 (Thanks!)