Ticket 47543 - Mozldap - fix compiler warnings
Fix these warnings:

../ds/ldap/servers/slapd/util.c: In function 'filter_stuff_func':
../ds/ldap/servers/slapd/util.c:257: warning: unused variable 'raw_filter'
../ds/ldap/servers/slapd/util.c:256: warning: unused variable 'escaped_filter'
../ds/ldap/servers/slapd/util.c: In function 'slapi_escape_filter_value':
../ds/ldap/servers/slapd/util.c:450: warning: unused variable 'raw_filter'
../ds/ldap/servers/slapd/util.c:449: warning: unused variable 'escaped_filter'
../ds/ldap/servers/plugins/posix-winsync/posix-winsync.c: In function 'sync_acct_disable':
../ds/ldap/servers/plugins/posix-winsync/posix-winsync.c:313: warning: implicit declaration of function 'strlen'
../ds/ldap/servers/plugins/posix-winsync/posix-winsync.c:313: warning: incompatible implicit declaration of built-in function 'strlen'
../ds/ldap/servers/plugins/posix-winsync/posix-group-task.c: In function 'posix_group_fix_memberuid_callback':
../ds/ldap/servers/plugins/posix-winsync/posix-group-task.c:283: warning: implicit declaration of function 'strlen'
../ds/ldap/servers/plugins/posix-winsync/posix-group-task.c:283: warning: incompatible implicit declaration of built-in function 'strlen'
../ds/ldap/servers/plugins/posix-winsync/posix-group-task.c:356: warning: implicit declaration of function 'strncasecmp'

https://fedorahosted.org/389/ticket/47543

Reviewed by: richm(Thanks!)
(cherry picked from commit 92f9e8393a2bc558fc77d569749199e987e25472)