Issue 5853 - Update Cargo.lock and fix minor warning (#5854)
Description: Run cargo update --manifest-path=./src/Cargo.toml.
Add minimum supported rust version field to the manifests.
Fix minor 'variable does not need to be mutable' error.

Another error:
error: using `.borrow()` on a double reference, which returns
`&concread::cowcell::CowCellReadTxn<CacheStats>` instead of borrowing the inner type

We're getting the error about borrowing a double reference because
we're trying to borrow a type that is already a reference.
Fix - use the type directly.
Set rust-version to 1.70 for better compatibility.

Related: https://github.com/389ds/389-ds-base/issues/5853
Fixes: https://github.com/389ds/389-ds-base/issues/5861

Reviewed by: @vashirov (Thanks!), @Firstyear (Thanks for the rust-version idea!)