Ticket #48934 - remove-ds.pl deletes an instance even if wrong prefix was specified
Description: remove-ds.pl skipped to check "slapd" part of "slapd-instance".
This patch adds the check and if it is not "slapd", it quits with the error
message.  For example:
Error: Invalid instance name "bogus-test"

https://fedorahosted.org/389/ticket/48934

Reviewed by mreynolds@redhat.com (Thanks, Mark!!)

(cherry picked from commit 2b341922a42f305122fbd6eb97e96e0612f8e5d2)