Ticket 48336 - Missing semanage dependency
Bug Description:  On a clean install

Traceback (most recent call last):
  File "/usr/sbin/ds_selinux_enabled", line 17, in <module>
    import semanage
ImportError: No module named semanage

Fix Description:  Add the proper dependency to the rpm so that we are not
missing the module.

https://fedorahosted.org/389/ticket/48336

Author: wibrown

Review by: mreynolds (Thanks!)